### ISSUE TITLE
Rename repo to "diamond_drops"

### ISSUE THREAD

**Issue by ChosunOne** [Drops-of-Diamond/diamond_drops#8]
Currently it's difficult to separate code into crates due to the name of the repo containing nonstandard naming.  This causes compiler errors when attempting to use the line:
``extern crate Diamond-drops;

I propose renaming the repo and associated files to the standard snake case "diamond_drops" to rectify the issue.  If there is another way to use crates with the current name then posting that here would be sufficient.

**Comment by jamesray1** [comment]
Done, let's keep it in mind for file names as well.
